name: pomo_panda
description: A Pomodoro timer app with stats tracking
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  http: ^1.2.0
  google_generative_ai: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  macos:
    generate: true
    image_path: "AppIcon-AppStore-1024.png"
  image_path: "AppIcon-AppStore-1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

